apiVersion: v1
appVersion: 2.204.1
description: The leading open source automation server
engine: gotpl
home: https://jenkins.io/
icon: https://bitnami.com/assets/stacks/jenkins/img/jenkins-stack-110x117.png
keywords:
- jenkins
- ci
- cd
- http
- web
- application
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: jenkins
sources:
- https://github.com/bitnami/bitnami-docker-jenkins
version: 4.1.1
