{{- if ne .Values.service.type "Ingress" }}
apiVersion: v1
kind: Service
metadata:
{{- if eq .Values.service.type "ClusterIP" }}
{{- $clusterIP := .Values.service.clusterIP }}
  name: {{ .Release.Name }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $clusterIP.ports.httpPort }}
      targetPort: 8080
    {{- if .Values.service.tls.enabled }}
    - name: https
      port: {{ $clusterIP.ports.httpsPort }}
      targetPort: 8443
    {{- end }}
    {{- if .Values.notary.enabled }}
    - name: notary
      port: {{ $clusterIP.ports.notaryPort }}
      targetPort: 4443
    {{- end }}
{{- else if eq .Values.service.type "NodePort" }}
{{- $nodePort := .Values.service.nodePort }}
  name: {{ .Release.Name }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ $nodePort.ports.http.port }}
      targetPort: 8080
      {{- if $nodePort.ports.http.nodePort }}
      nodePort: {{ $nodePort.ports.http.nodePort }}
      {{- end }}
    {{- if .Values.service.tls.enabled }}
    - name: https
      port: {{ $nodePort.ports.https.port }}
      targetPort: 8443
      {{- if $nodePort.ports.https.nodePort }}
      nodePort: {{ $nodePort.ports.https.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.notary.enabled }}
    - name: notary
      port: {{ $nodePort.ports.notary.port }}
      targetPort: 4443
      {{- if $nodePort.ports.notary.nodePort }}
      nodePort: {{ $nodePort.ports.notary.nodePort }}
      {{- end }}
    {{- end }}
{{- else if eq .Values.service.type "LoadBalancer" }}
{{- $loadBalancer := .Values.service.loadBalancer }}
  name: {{ .Release.Name }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
  {{- with $loadBalancer.annotations }}
    annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- with $loadBalancer.sourceRanges }}
    loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ $loadBalancer.ports.httpPort }}
      targetPort: 8080
    {{- if .Values.service.tls.enabled }}
    - name: https
      port: {{ $loadBalancer.ports.httpsPort }}
      targetPort: 8443
    {{- end }}
    {{- if .Values.notary.enabled }}
    - name: notary
      port: {{ $loadBalancer.ports.notaryPort }}
      targetPort: 4443
    {{- end }}
{{- end }}
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
