apiVersion: v1
appVersion: 1.12.0
description: Weave Scope 是 Docker 和 Kubernetes 可视化监控工具。
home: https://www.weave.works/olocal/scope/
icon: local://weave-scope-110x117.png
keywords:
- Management
maintainers:
- email: github@orion-com.com
  name: omkensey
- email: daniel@weave.works
  name: dholbach
- email: filip@weave.works
  name: fbarl
- email: bryan@weave.works
  name: bboreham
name: weave-scope
sources:
- https://github.com/weaveworks/scope
version: 1.1.10
